#!/usr/bin/env -S deno run -A

// 拒绝在 物理机 运行
async function 检查虚拟机() {
  const c = new Deno.Command("systemd-detect-virt", {
    args: ["--vm"],
    stdin: "null",
    stderr: "inherit",
  });
  const { code, stdout } = await c.output();
  const r = new TextDecoder().decode(stdout);

  console.error(`ds-agent run in [${r.trim()}] (systemd-detect-virt --vm)`);
  if (0 != code) {
    console.error("ERROR: ds-agent must run in a virtual machine, exit !");
    Deno.exit(1);
  }
}

async function main() {
  await 检查虚拟机();

  console.log("TODO");
}

await main();
